### ISSUE TITLE
Win 下 Ctrl-C、查找问题/答案后无响应，和一个说明文档的建议

### ISSUE THREAD

**Issue by SyuueenN** [Nana-Miko/ChatLearning#28]
Win11 版本 22000.556，Terminal 版本 1.11.3471.0，PowerShell 版本 5.1.22000.282，mirai 版本 2.11.0-M1，CL 版本 2.6.0。

1、建议在文档中补充一些容易令人困惑部分的说明，如 !setvoicept 的参数可以用那些、去哪儿找。
以及 .cl 词库文件的手动编辑用的格式说明，实际找规律时感觉痛不欲生。如果说为什么要手动找的话，~~毕竟都已经自我折磨来玩命令行程序了笑~~因为总有需求还是要靠查找替换来完成，总依赖 po 主来更新功能那开发工作也太辛苦了。

2、在控制台中 Ctrl-C 退出时，只会输出错误而不退出，然后对任何输入无响应。此时只能手动关闭标签页。
这是控制台输出。使用 Win11 内置 Terminal 的 PowerShell 运行。

```
PS E:\DroneBase\mirai-windows-amd64\_mods\ChatLearning.Windows> .\Chatmain.exe
欢迎使用ChatLearning应用 版本号： 2.6.0
输入help来查看指令列表吧！

ChatLearning ->
ChatLearning控制台无法加载，可能是置于后台运行
_
```

3、在查找过问题/答案后，总是输出错误然后对任何输入无响应，只能手动关闭并重启，这是聊天记录和错误输出。

```
SyuueenN 02:02:19
!admin

COURRIER 02:02:19
停止记录

COURRIER 02:02:20
关闭回复功能

COURRIER 02:02:22
请发送需要操作的序号
1.在所有群内查找
2.在指定群内查找
3.过滤设置

SyuueenN 02:02:24
1

COURRIER 02:02:25
请选择你的操作
1.查找问题
2.查找答案
3.查看某个群的所有词库
4.退出管理模式

SyuueenN 02:02:31
1

COURRIER 02:02:31
请发送关键字

SyuueenN 02:02:38
10086

COURRIER 02:02:39
查找中……

COURRIER 02:02:39
共找到1个符合的问题
群710338078 找到1个

COURRIER 02:02:40
请输入你的选择
1.返回查找结果
2.继续查找
3.返回

SyuueenN 02:02:42
1

（静————）

SyuueenN 02:03:02
!admin

（静————）
```

```
抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chatlearning-clxls-1302376822.cos.ap-shanghai.myqcloud.com')
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qcloud_cos\cos_client.py", line 302, in send_request
  File "requests\sessions.py", line 589, in put
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='chatlearning-clxls-1302376822.cos.ap-shanghai.myqcloud.com', po)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ChatClass.py", line 103, in run
  File "Chatmain.py", line 935, in getcommand_chat
  File "Chatmain.py", line 1043, in commandchoice
  File "Chatmain.py", line 276, in admin
  File "ChatAllfind.py", line 638, in findallcontrol
  File "ChatAllfind.py", line 514, in findallquestion
  File "ChatAllfind.py", line 217, in uploadcos
  File "qcloud_cos\cos_client.py", line 3395, in upload_file
  File "qcloud_cos\cos_client.py", line 380, in put_object
  File "qcloud_cos\cos_client.py", line 321, in send_request
qcloud_cos.cos_exception.CosClientError: HTTPSConnectionPool(host='chatlearning-clxls-1302376822.cos.ap-shanghai.myqclo)
```

**Comment by Nana-Miko** [comment]
目前的话有一个说明文档的网站正在上线中，然后setvoice的参数其实在
![{SV9$CNQDDGV187YG2LNE{B](https://user-images.githubusercontent.com/46672817/160508269-f583266f-f4f7-42d0-9c5e-a2a704036a8c.png)
这里有说明，可能我没写清楚
如果要手动编辑的话，那个格式就算知道了但是易读性不高，建议用[这个工具](https://github.com/Nana-Miko/ChatLearning/releases/tag/ClTools)先转换后再编辑，这个是[使用说明](https://github.com/Nana-Miko/ChatLearning/blob/master/tools/README.md)

Ctrl+C刚刚我试了，windows确实只能手动关闭窗口，但是linux是正常的，我看能不能尝试修复一下

这个报错是没能成功访问腾讯云那边的服务器，应该是您这边网路的问题，是不是有挂代理什么的？我下次更新加个异常捕捉吧，这样出错不用重新开软件

**Comment by SyuueenN** [comment]
> 

谢谢耐心解答！好像确实是没有仔细找的问题，这下就明白了。修 bug 辛苦了。

**Comment by Nana-Miko** [comment]
> > 
> 
> 谢谢耐心解答！好像确实是没有仔细找的问题，这下就明白了。修 bug 辛苦了。

嗯嗯！
