### ISSUE TITLE
所有的回复都会显示被过滤

### ISSUE THREAD

**Issue by rogue233** [Nana-Miko/ChatLearning#47]
无法回复任何信息，包括自动触发的语音。控制台提示【已过滤，原因：与过滤名单模糊匹配】但我把后台过滤名单删了也还是一样。

**Comment by Nana-Miko** [comment]
你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的

**Comment by rogue233** [comment]
> 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的

哦，确实有消息类型。但这个怎么改，配置文件没有这个，而且文字转语音固定需要艾特啊

**Comment by rogue233** [comment]
> 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的

哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
使用主动文字转原因控制台回显也是转换失败

**Comment by Nana-Miko** [comment]
> > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> 
> 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> 使用主动文字转原因控制台回显也是转换失败

选择了训练集嘛，之前有没有uploadwav成功?

**Comment by rogue233** [comment]
> > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > 
> > 
> > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > 使用主动文字转原因控制台回显也是转换失败
> 
> 选择了训练集嘛，之前有没有uploadwav成功?

选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）

**Comment by Nana-Miko** [comment]
> > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > 
> > > 
> > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > 使用主动文字转原因控制台回显也是转换失败
> > 
> > 选择了训练集嘛，之前有没有uploadwav成功?
> 
> 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）

试试把程序拖到cmd里面运行，我好看看报错信息

**Comment by rogue233** [comment]
> > > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > > 
> > > > 
> > > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > > 使用主动文字转原因控制台回显也是转换失败
> > > 
> > > 
> > > 选择了训练集嘛，之前有没有uploadwav成功?
> > 
> > 
> > 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）
> 
> 试试把程序拖到cmd里面运行，我好看看报错信息

![图片](https://user-images.githubusercontent.com/80617099/179909613-9a5029e8-544b-4946-a90c-bcc869622102.png)

**Comment by Nana-Miko** [comment]
> 
> 
> 
> > > > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > > > 
> > > > > 
> > > > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > > > 使用主动文字转原因控制台回显也是转换失败
> > > > 
> > > > 
> > > > 选择了训练集嘛，之前有没有uploadwav成功?
> > > 
> > > 
> > > 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）
> > 
> > 试试把程序拖到cmd里面运行，我好看看报错信息
> 
> ![图片](https://user-images.githubusercontent.com/80617099/179909613-9a5029e8-544b-4946-a90c-bcc869622102.png)
> 

在程序目录下打开cmd再拖到里面运行

**Comment by rogue233** [comment]
> > > > > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > > > > 
> > > > > > 
> > > > > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > > > > 使用主动文字转原因控制台回显也是转换失败
> > > > > 
> > > > > 
> > > > > 选择了训练集嘛，之前有没有uploadwav成功?
> > > > 
> > > > 
> > > > 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）
> > > 
> > > 
> > > 试试把程序拖到cmd里面运行，我好看看报错信息
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/80617099/179909613-9a5029e8-544b-4946-a90c-bcc869622102.png)
> 
> 在程序目录下打开cmd再拖到里面运行

ChatLearning ->uploadwav
Traceback (most recent call last):
  File "asyncio\tasks.py", line 258, in __step
  File "prompt_toolkit\application\application.py", line 1070, in _poll_output_s
ize
  File "asyncio\tasks.py", line 654, in sleep
  File "asyncio\futures.py", line 284, in __await__
  File "asyncio\tasks.py", line 328, in __wakeup
  File "asyncio\futures.py", line 196, in result
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prompt_toolkit\application\application.py", line 1051, in cancel_and_wai
t_for_background_tasks
  File "asyncio\futures.py", line 284, in __await__
  File "asyncio\tasks.py", line 328, in __wakeup
  File "asyncio\futures.py", line 196, in result
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Chatmain.py", line 2094, in <module>
  File "nest_asyncio.py", line 89, in run_until_complete
  File "asyncio\futures.py", line 201, in result
  File "asyncio\tasks.py", line 258, in __step
  File "Chatmain.py", line 1912, in getcommand_tui
  File "Chatmain.py", line 1955, in commandchoice
  File "Chatmain.py", line 459, in uploadwav
  File "wave.py", line 509, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 130, in initfp
wave.Error: file does not start with RIFF id
[1812] Failed to execute script 'Chatmain' due to unhandled exception!

![图片](https://user-images.githubusercontent.com/80617099/179911967-c66f023d-e0aa-4847-b920-495042d6d816.png)

**Comment by Nana-Miko** [comment]
> > > > > > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > > > > > 
> > > > > > > 
> > > > > > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > > > > > 使用主动文字转原因控制台回显也是转换失败
> > > > > > 
> > > > > > 
> > > > > > 选择了训练集嘛，之前有没有uploadwav成功?
> > > > > 
> > > > > 
> > > > > 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）
> > > > 
> > > > 
> > > > 试试把程序拖到cmd里面运行，我好看看报错信息
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/80617099/179909613-9a5029e8-544b-4946-a90c-bcc869622102.png)
> > 
> > 在程序目录下打开cmd再拖到里面运行
> 
> ChatLearning ->uploadwav
> Traceback (most recent call last):
>   File "asyncio\tasks.py", line 258, in __step
>   File "prompt_toolkit\application\application.py", line 1070, in _poll_output_s
> ize
>   File "asyncio\tasks.py", line 654, in sleep
>   File "asyncio\futures.py", line 284, in __await__
>   File "asyncio\tasks.py", line 328, in __wakeup
>   File "asyncio\futures.py", line 196, in result
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "prompt_toolkit\application\application.py", line 1051, in cancel_and_wai
> t_for_background_tasks
>   File "asyncio\futures.py", line 284, in __await__
>   File "asyncio\tasks.py", line 328, in __wakeup
>   File "asyncio\futures.py", line 196, in result
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Chatmain.py", line 2094, in <module>
>   File "nest_asyncio.py", line 89, in run_until_complete
>   File "asyncio\futures.py", line 201, in result
>   File "asyncio\tasks.py", line 258, in __step
>   File "Chatmain.py", line 1912, in getcommand_tui
>   File "Chatmain.py", line 1955, in commandchoice
>   File "Chatmain.py", line 459, in uploadwav
>   File "wave.py", line 509, in open
>   File "wave.py", line 163, in __init__
>   File "wave.py", line 130, in initfp
> wave.Error: file does not start with RIFF id
> [1812] Failed to execute script 'Chatmain' due to unhandled exception!
> 
> ![图片](https://user-images.githubusercontent.com/80617099/179911967-c66f023d-e0aa-4847-b920-495042d6d816.png)
> 

用格式工厂来转wav格式的音频

**Comment by rogue233** [comment]
> > > > > > > > > 你仔细看看，是不是写着消息类型?默认过滤艾特，戳一戳和回复的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 哦哦，确实，但我看了下文字转换语音失败应该不是这个原因。似乎是因为其他原因，我尝试重新执行【uploadwav】命令，但是会直接闪退。
> > > > > > > > 使用主动文字转原因控制台回显也是转换失败
> > > > > > > 
> > > > > > > 
> > > > > > > 选择了训练集嘛，之前有没有uploadwav成功?
> > > > > > 
> > > > > > 
> > > > > > 选择了，之前都是可以，最近机器人被风控就换了一个，发现无法转换语音，之后就是重新搭建了一下还是不行，而且无法上传文件（只有几百k）
> > > > > 
> > > > > 
> > > > > 试试把程序拖到cmd里面运行，我好看看报错信息
> > > > 
> > > > 
> > > > ![图片](https://user-images.githubusercontent.com/80617099/179909613-9a5029e8-544b-4946-a90c-bcc869622102.png)
> > > 
> > > 
> > > 在程序目录下打开cmd再拖到里面运行
> > 
> > 
> > ChatLearning ->uploadwav
> > Traceback (most recent call last):
> > File "asyncio\tasks.py", line 258, in __step
> > File "prompt_toolkit\application\application.py", line 1070, in _poll_output_s
> > ize
> > File "asyncio\tasks.py", line 654, in sleep
> > File "asyncio\futures.py", line 284, in **await**
> > File "asyncio\tasks.py", line 328, in __wakeup
> > File "asyncio\futures.py", line 196, in result
> > asyncio.exceptions.CancelledError
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "prompt_toolkit\application\application.py", line 1051, in cancel_and_wai
> > t_for_background_tasks
> > File "asyncio\futures.py", line 284, in **await**
> > File "asyncio\tasks.py", line 328, in __wakeup
> > File "asyncio\futures.py", line 196, in result
> > asyncio.exceptions.CancelledError
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "Chatmain.py", line 2094, in 
> > File "nest_asyncio.py", line 89, in run_until_complete
> > File "asyncio\futures.py", line 201, in result
> > File "asyncio\tasks.py", line 258, in __step
> > File "Chatmain.py", line 1912, in getcommand_tui
> > File "Chatmain.py", line 1955, in commandchoice
> > File "Chatmain.py", line 459, in uploadwav
> > File "wave.py", line 509, in open
> > File "wave.py", line 163, in **init**
> > File "wave.py", line 130, in initfp
> > wave.Error: file does not start with RIFF id
> > [1812] Failed to execute script 'Chatmain' due to unhandled exception!
> > ![图片](https://user-images.githubusercontent.com/80617099/179911967-c66f023d-e0aa-4847-b920-495042d6d816.png)
> 
> 用格式工厂来转wav格式的音频

确实是这个问题，感谢！
