### ISSUE TITLE
响应完第一条命令后续命令不再响应

### ISSUE THREAD

**Issue by greenhandzdl** [Nana-Miko/ChatLearning#50]
不确定是哪一步的问题
```
linux1@gservice:/mirai$ cat develop/Source/start.sh
#!/bin/bash
nohup python3 /mirai/develop/Source/Chatmain.py > /mirai/develop/Source/log_n.txt &
```
```
linux1@gservice:/mirai$ cat develop/Source/log_n.txt
Warning: Input is not a terminal (fd=0).
欢迎使用ChatLearning应用 版本号： 2.9.8
输入help来查看指令列表吧！
<-开始记录
2022-07-23 05:42:46 词库合并完成
<-开启回复功能
抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "/mirai/develop/Source/ChatClass.py", line 375, in run
    self._target(*self._args, **self._kwargs)
  File "/mirai/develop/Source/Chatmain.py", line 1854, in getcommand_chat
    message = simuse.Fetch_Message(data)
  File "/mirai/develop/Source/simuse.py", line 89, in Fetch_Message
    Message = res['data']
KeyError: 'data'
```

![image](https://user-images.githubusercontent.com/61241103/180592280-174373c6-5f96-4202-b1c6-269ed6a891f9.png)

**Comment by Nana-Miko** [comment]
后台是掉了么，我看这个log时间不太对

**Comment by greenhandzdl** [comment]
完蛋，我卡起来了，不知道是网卡还是服务器卡

**Comment by Nana-Miko** [comment]
> 完蛋，我卡起来了，不知道是网卡还是服务器卡

草
