### ISSUE TITLE
3.0.0查看过滤关键字时报错

### ISSUE THREAD

**Issue by lizbaka** [Nana-Miko/ChatLearning#53]
我在linux环境下通过源码来运行bot
在我自己的机器上的复现方法：
- 私聊bot```!admin```进入管理模式
- 依次发送```3``` ```5``` ```1```查看过滤关键字
- 控制台报错，输出以下报错内容到```log.log```，同时bot不再响应私聊命令
```
Traceback (most recent call last):
  File "***/ChatClass.py", line 379, in run
    self._target(*self._args, **self._kwargs)
  File "***/Chatmain.py", line 1906, in getcommand_chat
    commandchoice(command['text'][1:], i['sender'])
  File "***/Chatmain.py", line 2034, in commandchoice
    adminsign = admin(adminsign, fromchat)
  File "***/Chatmain.py", line 842, in admin
    ChatFilter.filtercontrol(data, fromchat)
  File "***/ChatFilter.py", line 564, in filtercontrol
    Accuratedict = Filterconfig['Accuratedict']
KeyError: 'Accuratedict'
```

**Comment by Nana-Miko** [comment]
已紧急修复，重新下载即可解决，论坛最新回复说明了一些bug的解决方法

**Comment by Nana-Miko** [comment]
了解 正在紧急修复

**Comment by Nana-Miko** [comment]
问题已修复，下载源已更换

**Comment by lizbaka** [comment]
已解决
