### ISSUE TITLE
进行词库删除时抛出异常无法工作

### ISSUE THREAD

**Issue by leekooyo** [Nana-Miko/ChatLearning#61]
Traceback (most recent call last):
  File "ChatClass.py", line 404, in run
  File "Chatmain.py", line 1906, in getcommand_chat
  File "Chatmain.py", line 2034, in commandchoice
  File "Chatmain.py", line 807, in admin
  File "ChatAllfind.py", line 730, in findallcontrol
  File "ChatAllfind.py", line 524, in findallquestion
  File "ChatAllfind.py", line 366, in delcl
KeyError: "[{'type': 'Plain', 'text': '我'}]"
不知道是不是删除过多引起的

**Comment by Nana-Miko** [comment]
目测应该不是，重启之后可以使用吗

**Comment by leekooyo** [comment]
重启以后能正常使用，但是一到删除命令时就抛出

**Comment by Nana-Miko** [comment]
会不会是过滤设置的锅?
