### ISSUE TITLE
合并词库多次抛出错误

### ISSUE THREAD

**Issue by haha-dream** [Nana-Miko/ChatLearning#66]
其一

> 2023-01-27 23:45:14
Traceback (most recent call last):
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatClass.py", line 407, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 96, in main
    getfile()
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 78, in getfile
    Mergedict = Merge(Mergedict, i)
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 25, in Merge
    cldict = pickle_load(open('WordStock/' + filename, 'rb'))
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatClass.py", line 46, in pickle_load
    obj = pickle.load(file)
EOFError: Ran out of input

其二

> 2023-01-26 00:45:28
Traceback (most recent call last):
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatClass.py", line 407, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 103, in main
    getfile()
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 78, in getfile
    Mergedict = Merge(Mergedict, i)
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatMerge.py", line 25, in Merge
    cldict = pickle_load(open('WordStock/' + filename, 'rb'))
  File "D:\Stuff\KoishiDiceBot\ChatLearning.Source\ChatClass.py", line 46, in pickle_load
    obj = pickle.load(file)
_pickle.UnpicklingError: pickle data was truncated

**Comment by PositionZer0** [comment]
同样的问题，我这里没有开启 cosmatch

**Comment by NumberSir** [comment]
同样的问题，在合并词库和清理词库时都有这个问题

**Comment by NumberSir** [comment]
> 其一
> 
> > 2023-01-07 21:51:11
> > Traceback (most recent call last):
> > File "ChatClass.py", line 407, in run
> > File "ChatMerge.py", line 96, in main
> > File "ChatMerge.py", line 78, in getfile
> > File "ChatMerge.py", line 25, in Merge
> > File "ChatClass.py", line 46, in pickle_load
> > EOFError: Ran out of input
> 
> 其二
> 
> > 2023-01-08 22:01:05
> > Traceback (most recent call last):
> > File "ChatClass.py", line 407, in run
> > File "ChatMerge.py", line 103, in main
> > File "ChatMerge.py", line 78, in getfile
> > File "ChatMerge.py", line 25, in Merge
> > File "ChatClass.py", line 46, in pickle_load
> > _pickle.UnpicklingError: pickle data was truncated
> 
> 进行了一些小测试，可能和cosmatch造成的性能消耗（词条录入词库堵塞）有关？

找到问题一（EOFError）的原因了（大概）
你找找有没有0KB的词库，删掉就好了

**Comment by Nana-Miko** [comment]
相关0kb bug会在3.0.3版本修复，正在打包中）
