### ISSUE TITLE
新手礼问抛出异常

### ISSUE THREAD

**Issue by JoyerLiu** [Nana-Miko/ChatLearning#74]
错误信息：
欢迎使用ChatLearning应用 版本号： 3.0.3
输入help来查看指令列表吧！
<-开始记录
2023-02-28 10:58:29 词库合并完成
抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "ChatClass.py", line 393, in run
  File "Chatmain.py", line 1965, in getcommand_chat
  File "simuse.py", line 89, in Fetch_Message
KeyError: 'data'

抛出异常，已记录到日志(log.log文件)
Traceback (most recent call last):
  File "ChatClass.py", line 393, in run
  File "ChatLearning.py", line 354, in main
  File "ChatLearning.py", line 168, in listening
  File "ChatLearning.py", line 126, in extractmessage
  File "simuse.py", line 89, in Fetch_Message
KeyError: 'data'

./data.json

{
 "Key": "",
 "host": "127.0.0.1",
 "port": "8099",
 "qq": "348xxxx691",
 "session": "XXX"
}

在老的Issues中似乎有与我出现同样情况，但是采用其方法未能解决问题，故开新Issue询问

**Comment by JoyerLiu** [comment]
已解决，只有mcl开启了验证设置了Key值，验证过后即可正常使用，另外作者这会不会是一个bug（
