### ISSUE TITLE
QQ私聊命令没反应，chatlearning cmd窗口可执行命令

### ISSUE THREAD

**Issue by DongGua-Jun** [Nana-Miko/ChatLearning#86]
[Desktop.zip](https://github.com/Nana-Miko/ChatLearning/files/11439466/Desktop.zip)
![image](https://github.com/Nana-Miko/ChatLearning/assets/75875483/edc51234-da99-4f76-9087-929c17e22c38)

merge.cl文件已经4m大小了，但bot目前还是哑巴状态

压缩包里的data.json的key与http api的一致就会报错：取得session失败。
不填key就不报错取得session失败……怪

**Comment by DongGua-Jun** [comment]
2023-05-10 15:43:41
Traceback (most recent call last):
  File "ChatClass.py", line 393, in run
  File "ChatCheck.py", line 169, in main
TypeError: 'NoneType' object is not subscriptable

还有一个check命令后报错日志

**Comment by DongGua-Jun** [comment]
把mirai http api的singlemode模式关了之后连上了
