### ISSUE TITLE
录入信息就报错

### ISSUE THREAD

**Issue by mcmc-erha** [Nana-Miko/ChatLearning#95]
Traceback (most recent call last):
  File "ChatClass.py", line 393, in run
  File "ChatLearning.py", line 354, in main
  File "ChatLearning.py", line 195, in listening
  File "ChatLearning.py", line 83, in creatanswer
KeyError: ''
删除0kb的也不行
录入信息就报错

**Comment by JHue58** [comment]
> Traceback (most recent call last):
>   File "ChatClass.py", line 393, in run
>   File "ChatLearning.py", line 354, in main
>   File "ChatLearning.py", line 195, in listening
>   File "ChatLearning.py", line 83, in creatanswer
> KeyError: ''
> 删除0kb的也不行
> 录入信息就报错

具体是录入什么信息？

**Comment by ryujou** [comment]
出现一样的问题，开启学习后，只要群里出现消息就抛出异常
2024-02-23 14:02:04
Traceback (most recent call last):
  File "ChatClass.py", line 379, in run
  File "ChatLearning.py", line 354, in main
  File "ChatLearning.py", line 195, in listening
  File "ChatLearning.py", line 83, in creatanswer
KeyError: '' 
回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。

**Comment by ryujou** [comment]
> > Traceback (most recent call last):
> > File "ChatClass.py", line 393, in run
> > File "ChatLearning.py", line 354, in main
> > File "ChatLearning.py", line 195, in listening
> > File "ChatLearning.py", line 83, in creatanswer
> > KeyError: ''
> > 删除0kb的也不行
> > 录入信息就报错
> 
> 具体是录入什么信息？

出现一样的问题，开启学习后，只要群里出现消息就抛出异常
2024-02-23 14:02:04
Traceback (most recent call last):
File "ChatClass.py", line 379, in run
File "ChatLearning.py", line 354, in main
File "ChatLearning.py", line 195, in listening
File "ChatLearning.py", line 83, in creatanswer
KeyError: ''
回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。

**Comment by ryujou** [comment]
> > > Traceback (most recent call last):
> > > File "ChatClass.py", line 393, in run
> > > File "ChatLearning.py", line 354, in main
> > > File "ChatLearning.py", line 195, in listening
> > > File "ChatLearning.py", line 83, in creatanswer
> > > KeyError: ''
> > > 删除0kb的也不行
> > > 录入信息就报错
> > 
> > 
> > 具体是录入什么信息？
> 
> 出现一样的问题，开启学习后，只要群里出现消息就抛出异常 2024-02-23 14:02:04 Traceback (most recent call last): File "ChatClass.py", line 379, in run File "ChatLearning.py", line 354, in main File "ChatLearning.py", line 195, in listening File "ChatLearning.py", line 83, in creatanswer KeyError: '' 回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。

使用源码在Linux下运行就没有报错

**Comment by JHue58** [comment]
> > > > Traceback (most recent call last):
> > > > File "ChatClass.py", line 393, in run
> > > > File "ChatLearning.py", line 354, in main
> > > > File "ChatLearning.py", line 195, in listening
> > > > File "ChatLearning.py", line 83, in creatanswer
> > > > KeyError: ''
> > > > 删除0kb的也不行
> > > > 录入信息就报错
> > > 
> > > 
> > > 具体是录入什么信息？
> > 
> > 
> > 出现一样的问题，开启学习后，只要群里出现消息就抛出异常 2024-02-23 14:02:04 Traceback (most recent call last): File "ChatClass.py", line 379, in run File "ChatLearning.py", line 354, in main File "ChatLearning.py", line 195, in listening File "ChatLearning.py", line 83, in creatanswer KeyError: '' 回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。
> 
> 使用源码在Linux下运行就没有报错

测试的时候有没有清空wordstock文件夹？

**Comment by ryujou** [comment]
> > > > > Traceback (most recent call last):
> > > > > File "ChatClass.py", line 393, in run
> > > > > File "ChatLearning.py", line 354, in main
> > > > > File "ChatLearning.py", line 195, in listening
> > > > > File "ChatLearning.py", line 83, in creatanswer
> > > > > KeyError: ''
> > > > > 删除0kb的也不行
> > > > > 录入信息就报错
> > > > 
> > > > 
> > > > 具体是录入什么信息？
> > > 
> > > 
> > > 出现一样的问题，开启学习后，只要群里出现消息就抛出异常 2024-02-23 14:02:04 Traceback (most recent call last): File "ChatClass.py", line 379, in run File "ChatLearning.py", line 354, in main File "ChatLearning.py", line 195, in listening File "ChatLearning.py", line 83, in creatanswer KeyError: '' 回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。
> > 
> > 
> > 使用源码在Linux下运行就没有报错
> 
> 测试的时候有没有清空wordstock文件夹？

清空了，删除了整个文件夹重新下载的release

**Comment by JHue58** [comment]
> > > > > > Traceback (most recent call last):
> > > > > > File "ChatClass.py", line 393, in run
> > > > > > File "ChatLearning.py", line 354, in main
> > > > > > File "ChatLearning.py", line 195, in listening
> > > > > > File "ChatLearning.py", line 83, in creatanswer
> > > > > > KeyError: ''
> > > > > > 删除0kb的也不行
> > > > > > 录入信息就报错
> > > > > 
> > > > > 
> > > > > 具体是录入什么信息？
> > > > 
> > > > 
> > > > 出现一样的问题，开启学习后，只要群里出现消息就抛出异常 2024-02-23 14:02:04 Traceback (most recent call last): File "ChatClass.py", line 379, in run File "ChatLearning.py", line 354, in main File "ChatLearning.py", line 195, in listening File "ChatLearning.py", line 83, in creatanswer KeyError: '' 回滚到3.0.0版本也一样，环境window和Linux都试了都是一样的报错。
> > > 
> > > 
> > > 使用源码在Linux下运行就没有报错
> > 
> > 测试的时候有没有清空wordstock文件夹？
> 
> 清空了，删除了整个文件夹重新下载的release

那这样有可能是api http出问题了，获取到的question为空，试试用2.3.3的api http
